import FiretrackConfiguration
import Foundation
import SwiftParser

/// Generates a type-safe Swift analytics contract from a Firetrack YAML configuration.
package struct SwiftAnalyticsGenerator {
    /// Creates a Swift analytics source generator.
    package init() {}

    /// Returns parseable Swift source for the supplied tracking configuration.
    package func generate(
        configuration: AnalyticsTrackingConfiguration,
        options: SwiftAnalyticsGeneratorOptions = .init(),
    ) throws -> String {
        let context = SwiftGenerationContext(
            configuration: configuration,
            access: options.accessLevel.declarationPrefix,
        )
        let source = render {
            header()
            analyticsValue(context: context)
            analyticsScreen(context: context)
            allowedValueEnums(context: context)
            analyticsEvent(context: context)
        }

        let parsed = Parser.parse(source: source)
        if parsed.hasError {
            throw SwiftAnalyticsGeneratorError.generatedSourceDidNotParse
        }
        return source
    }

    private func render(@SwiftSourceBuilder _ content: () -> [String]) -> String {
        content().joined(separator: "\n")
    }

    @SwiftSourceBuilder
    private func header() -> [String] {
        "// Generated by Firetrack. Do not edit by hand."
        ""
        "import Foundation"
        ""
    }

    @SwiftSourceBuilder
    private func analyticsValue(context: SwiftGenerationContext) -> [String] {
        """
        \(context.access)enum AnalyticsValue: Equatable, Sendable {
            case string(String)
            case int(Int)
            case double(Double)
            case bool(Bool)
        }
        """
        ""
    }

    @SwiftSourceBuilder
    private func analyticsScreen(context: SwiftGenerationContext) -> [String] {
        "\(context.access)enum AnalyticsScreen: String, CaseIterable, Sendable {"
        for screenName in context.configuration.screens.keys.sorted() {
            "    case \(screenName.lowerCamelCased()) = \"\(screenName)\""
        }
        "}"
        ""
    }

    @SwiftSourceBuilder
    private func allowedValueEnums(context: SwiftGenerationContext) -> [String] {
        let definitions = GA4DesiredStateExtractor.parameterDefinitions(context.configuration)
        for parameterName in definitions.keys.sorted() {
            let allowed = definitions[parameterName]?.allowed ?? []
            if !allowed.isEmpty {
                allowedValueEnum(parameterName: parameterName, allowed: allowed, access: context.access)
            }
        }
    }

    @SwiftSourceBuilder
    private func allowedValueEnum(parameterName: String, allowed: [String], access: String) -> [String] {
        "\(access)enum \(parameterName.upperCamelCased())Value: String, CaseIterable, Sendable {"
        for value in allowed.sorted() {
            "    case \(value.lowerCamelCased()) = \"\(value)\""
        }
        "}"
        ""
    }

    @SwiftSourceBuilder
    private func analyticsEvent(context: SwiftGenerationContext) -> [String] {
        "\(context.access)enum AnalyticsEvent: Equatable, Sendable {"
        eventCases(context: context)
        ""
        eventNameProperty(context: context)
        ""
        eventParametersProperty(context: context)
        "}"
        ""
    }

    @SwiftSourceBuilder
    private func eventCases(context: SwiftGenerationContext) -> [String] {
        for (eventName, event) in context.configuration.events.sorted(by: { $0.key < $1.key }) {
            let parameters = effectiveParameters(for: event, configuration: context.configuration)
            if parameters.isEmpty {
                "    case \(eventName.lowerCamelCased())"
            } else {
                "    case \(eventName.lowerCamelCased())(\(associatedValues(for: parameters)))"
            }
        }
    }

    @SwiftSourceBuilder
    private func eventNameProperty(context: SwiftGenerationContext) -> [String] {
        "    \(context.access)var name: String {"
        "        switch self {"
        for eventName in context.configuration.events.keys.sorted() {
            "        case .\(eventName.lowerCamelCased()): \"\(eventName)\""
        }
        "        }"
        "    }"
    }

    @SwiftSourceBuilder
    private func eventParametersProperty(context: SwiftGenerationContext) -> [String] {
        "    \(context.access)var parameters: [String: AnalyticsValue] {"
        "        switch self {"
        for (eventName, event) in context.configuration.events.sorted(by: { $0.key < $1.key }) {
            parameterSwitchCase(eventName: eventName, event: event, context: context)
        }
        "        }"
        "    }"
    }

    @SwiftSourceBuilder
    private func parameterSwitchCase(
        eventName: String,
        event: AnalyticsEventConfiguration,
        context: SwiftGenerationContext,
    ) -> [String] {
        let parameters = effectiveParameters(for: event, configuration: context.configuration)
        if parameters.isEmpty {
            "        case .\(eventName.lowerCamelCased()):"
            "            return [:]"
        } else {
            let bindings = parameters.map { $0.key.lowerCamelCased() }.joined(separator: ", ")
            "        case let .\(eventName.lowerCamelCased())(\(bindings)):"
            "            var parameters: [String: AnalyticsValue] = [:]"
            parameterAssignments(parameters)
            "            return parameters"
        }
    }

    @SwiftSourceBuilder
    private func parameterAssignments(
        _ parameters: [(key: String, value: AnalyticsParameterConfiguration)],
    ) -> [String] {
        for (name, parameter) in parameters {
            let localName = name.lowerCamelCased()
            let expression = analyticsValueExpression(localName: localName, parameter: parameter)
            if parameter.required == true {
                "            parameters[\"\(name)\"] = \(expression)"
            } else {
                "            if let \(localName) {"
                "                parameters[\"\(name)\"] = \(expression)"
                "            }"
            }
        }
    }

    private func associatedValues(for parameters: [(key: String, value: AnalyticsParameterConfiguration)]) -> String {
        parameters.map { name, parameter in
            let type = swiftType(for: parameter, parameterName: name)
            return "\(name.lowerCamelCased()): \(type)\(parameter.required == true ? "" : "?")"
        }.joined(separator: ", ")
    }

    private func swiftType(for parameter: AnalyticsParameterConfiguration, parameterName: String) -> String {
        switch parameter.type {
        case .string:
            "String"
        case .enumeration:
            parameter.allowed?.isEmpty == false ? "\(parameterName.upperCamelCased())Value" : "String"
        case .int:
            "Int"
        case .double:
            "Double"
        case .bool:
            "Bool"
        }
    }

    private func effectiveParameters(
        for event: AnalyticsEventConfiguration,
        configuration: AnalyticsTrackingConfiguration,
    ) -> [(key: String, value: AnalyticsParameterConfiguration)] {
        event.parameters
            .map { name, parameter in
                (name, configuration.globalParameters[name]?.merging(parameter) ?? parameter)
            }
            .sorted { $0.key < $1.key }
    }

    private func analyticsValueExpression(localName: String, parameter: AnalyticsParameterConfiguration) -> String {
        switch parameter.type {
        case .string:
            ".string(\(localName))"
        case .enumeration:
            parameter.allowed?.isEmpty == false ? ".string(\(localName).rawValue)" : ".string(\(localName))"
        case .int:
            ".int(\(localName))"
        case .double:
            ".double(\(localName))"
        case .bool:
            ".bool(\(localName))"
        }
    }
}

private struct SwiftGenerationContext {
    var configuration: AnalyticsTrackingConfiguration
    var access: String
}
