import Foundation
import SwiftSyntax

extension SwiftAnalyticsGenerator {
    /// Joins top-level declarations into a formatted source file: a generated header, an import,
    /// then each declaration separated by a blank line — matching swiftformat's layout.
    static func render(_ declarations: [DeclSyntaxProtocol]) -> String {
        let body = declarations
            .map { $0.formatted().description }
            .joined(separator: "\n\n")
        return """
        // Generated by Firetrack. Do not edit by hand.

        import Foundation

        \(body)

        """
    }
}

extension SwiftAccessLevel {
    /// The `public ` / `package ` prefix written before a declaration, or empty for internal.
    var extensionModifierPrefix: String {
        self == .internal ? "" : "\(rawValue) "
    }
}
